### ISSUE TITLE
Prepare test data

### ISSUE THREAD

**Issue by vkbo** [metno/AnnotatedAtlas#7]
Make sure a test database and CAP files are available for building code in Sprint 1.

**Comment by fzeiser** [comment]
From Helen:

> Det finnes en CouchDB database, men det finnes ikke noe særlig data der foreløpig, kun noen testvarsler som er laget nå i vår. De ligger da også kun i Jsonformat, ikke CAP. 
> Det beste er antagligvis å hente CAP-filene fra `/lustre/storeB/immutable/archive/projects/metproduction/DNMI_VARSLER/`  hvor de ligger sortert på dato, f.eks.  `/lustre/storeB/immutable/archive/projects/metproduction/DNMI_VARSLER/2021/06/13/METfare-20210613T073650.cap.xml`,  tror de bare finnes fra 2018 og senere).
> 
> Polygonene kan hentes fra Statens Kartverk, det ser ut som denne siden kan være nyttig: https://www.kartverket.no/api-og-data/grensedata
>

**Comment by fzeiser** [comment]
- Kartverket polygons can be accessed through script uploaded in https://github.com/metno/MetAlert-Search/pull/10
- CAP files accessible as described above. 

@vkbo: Found the description of the cap file content in
http://docs.oasis-open.org/emergency/cap/v1.2/CAP-v1.2-os.html

Section `3.2.4    "area" Element and Sub-elements` has more information. One or several `<area>` blocks with one of several `<polyon>` bloack may be defined. These are paired values of **WGS84** lat lon coordinates.
Example section from `less `/lustre/storeB/immutable/archive/projects/metproduction/DNMI_VARSLER/2021/06/13/METfare-20210613T073650.cap.xml`:

```
    <area>
      <areaDesc>Måløy - Svinøy</areaDesc>
      <polygon>62.217167,4.932500 62.043000,4.760167 62.021667,5.019333 62.183833,5.141000 62.265500,5.446000 62.360333,5.222667 62.217167,4.932500
</polygon>
```

**Comment by fzeiser** [comment]
Note: A test database is available, but does not contain any CAP files yet, so I think that we can work with the CAP files directly.
